//  Translated by epsc  version: Fri Jan  2 16:12:14 2026

#include <stddef.h>
#include <stdio.h>
#include <assert.h>
typedef struct { float r; float i;} complex; 
typedef struct nctempfloat1 { int d[1]; float *a;} nctempfloat1; 
typedef struct nctempint1 { int d[1]; int *a;} nctempint1; 
typedef struct nctempchar1 { int d[1]; char *a;} nctempchar1; 
typedef struct nctempcomplex1 { int d[1]; complex *a;} nctempcomplex1; 
typedef struct nctempfloat2 { int d[2]; float *a;} nctempfloat2; 
typedef struct nctempint2 { int d[2]; int *a;} nctempint2; 
typedef struct nctempchar2 { int d[2]; char *a;} nctempchar2; 
typedef struct nctempcomplex2 { int d[2]; complex *a;} nctempcomplex2; 
typedef struct nctempfloat3 { int d[3]; float *a;} nctempfloat3; 
typedef struct nctempint3 { int d[3]; int *a;} nctempint3; 
typedef struct nctempchar3 { int d[3]; char *a;} nctempchar3; 
typedef struct nctempcomplex3 { int d[3]; complex *a;} nctempcomplex3; 
typedef struct nctempfloat4 { int d[4]; float *a;} nctempfloat4; 
typedef struct nctempint4 { int d[4]; int *a;} nctempint4; 
typedef struct nctempchar4 { int d[4]; char *a;} nctempchar4; 
typedef struct nctempcomplex4 { int d[4]; complex *a;} nctempcomplex4; 
#include <stdlib.h>
#include <string.h>
void *RunMalloc(int n); 
int RunFree(void *n); 
struct MainArg {nctempchar1 *arg;
};
typedef struct nctempMainArg1 {int d[1]; struct MainArg *a; } nctempMainArg1;
struct nctempMainArg2 {int d[2]; struct MainArg *a; } ;
struct nctempMainArg3 {int d[3]; struct MainArg *a; } ;
struct nctempMainArg4 {int d[4]; struct MainArg *a; } ;
int LibeErrinit ();
int LibeGeterrno ();
int LibeClearerr ();
nctempchar1 * LibeGeterrstr ();
nctempchar1 * LibeGetenv (nctempchar1 *name);
float LibeMach (int flag);
float LibeFabs (float x);
float LibeFscale2 (float x,int n);
float LibeGetfman2 (float x);
int LibeGetfexp2 (float x);
float LibeFscale (float x,int n);
int LibeGetfman (float f,int maxdig);
float LibeGetffman (float f);
int LibeGetmaxdig (float f);
int LibeGetfexp (float f);
float LibeClock ();
int LibeMod (int n,int r);
float LibeSqrt (float x);
float LibeLn (float x);
float LibeExp (float x);
float LibeSincos (float x,float y,float sign);
float LibeSin (float x);
float LibeCos (float x);
float LibeTan (float x);
float LibeArcsin (float x);
float LibeArccos (float x);
float LibeAtan (float f);
float LibeArctan (float x);
float LibePow (float base,float exponent);
int LibeMathinit ();
int LibeStrlen (nctempchar1 *s);
int LibeStrcmp (nctempchar1 *s,nctempchar1 *t);
int LibeStrev (nctempchar1 *s);
int LibeStrcpy (nctempchar1 *s,nctempchar1 *t);
int LibeStrcat (nctempchar1 *s,nctempchar1 *t);
nctempchar1 * LibeStradd (nctempchar1 *t,nctempchar1 *s);
nctempchar1 * LibeStrsave (nctempchar1 *s);
int LibeIsalhpa (int c);
int LibeIsdigit (int c);
int LibeIsalnum (int c);
int LibeAtoi (nctempchar1 *s);
int LibeItoa (int n,nctempchar1 *s);
int LibeItoh (int n,nctempchar1 *s);
float LibeAtof (nctempchar1 *s);
int LibeFtoaf (int mant,int nexp,int nfield,int nfrac,nctempchar1 *s);
int LibeFtoae (int mant,int nexp,int nfield,int nfrac,nctempchar1 *s);
int LibeFtoa (float f,nctempchar1 *fmt,nctempchar1 *s);
struct LibeFdescr {int cnt;
int ptr;
int bufsize;
nctempchar1 *base;
int readflg;
int writflg;
int unbflg;
int errflg;
int eoflg;
int fd;
};
typedef struct nctempLibeFdescr1 {int d[1]; struct LibeFdescr *a; } nctempLibeFdescr1;
struct nctempLibeFdescr2 {int d[2]; struct LibeFdescr *a; } ;
struct nctempLibeFdescr3 {int d[3]; struct LibeFdescr *a; } ;
struct nctempLibeFdescr4 {int d[4]; struct LibeFdescr *a; } ;
int LibeIoinit ();
int LibeFlushbuff (int fp);
int LibeFillbuff (int fp);
int LibeFlush (int fp);
int LibeOpen (nctempchar1 *name,nctempchar1 *mode);
int LibeClose (int fp);
int LibeGetc (int fp);
int LibeUngetc (int fp);
int LibeGetw (int fp,nctempchar1 *text);
int LibePutc (int fp,int c);
int LibePuts (int fp,nctempchar1 *s);
int LibePuti (int fp,int ival);
int LibePutf (int fp,float fval,nctempchar1 *form);
int LibePs (nctempchar1 *s);
int LibePi (int n);
int LibePf (float r);
int LibeRead (int fp,int n,nctempchar1 *buffer);
int LibeWrite (int fp,int n,nctempchar1 *buffer);
int LibeSeek (int fp,int pos,int flag);
int LibeIodelete ();
int LibeSetnb (int nb);
int LibeSetnt (int nt);
int LibeGetnb ();
int LibeGetnt ();
int LibeArrayex (int line,nctempchar1 *name,int ival,int index,int bound);
int LibeSystem (nctempchar1 *cmd);
int LibeInit ();
int LibeExit ();
nctempchar1 * LibeDate ();
int ErrError (nctempchar1 *file,int line,nctempchar1 *s)
{
int nctemp2= 4;
struct nctempchar1 *nctemp6;
static struct nctempchar1 nctemp7 = {{ 7}, (char*)"file: \0"};
nctemp6=&nctemp7;
nctempchar1* nctemp4= nctemp6;
int nctemp8=LibePuts(nctemp2,nctemp4);
int nctemp10= 4;
nctempchar1* nctemp12= file;
int nctemp15=LibePuts(nctemp10,nctemp12);
int nctemp17= 4;
struct nctempchar1 *nctemp21;
static struct nctempchar1 nctemp22 = {{ 10}, (char*)" -- line \0"};
nctemp21=&nctemp22;
nctempchar1* nctemp19= nctemp21;
int nctemp23=LibePuts(nctemp17,nctemp19);
int nctemp25= 4;
int nctemp27= line;
int nctemp29=LibePuti(nctemp25,nctemp27);
int nctemp31= 4;
struct nctempchar1 *nctemp35;
static struct nctempchar1 nctemp36 = {{ 4}, (char*)" : \0"};
nctemp35=&nctemp36;
nctempchar1* nctemp33= nctemp35;
int nctemp37=LibePuts(nctemp31,nctemp33);
int nctemp39= 4;
nctempchar1* nctemp43= s;
nctempchar1* nctemp46=LibeStrsave(nctemp43);
nctempchar1* nctemp41= nctemp46;
int nctemp47=LibePuts(nctemp39,nctemp41);
int nctemp49= 4;
struct nctempchar1 *nctemp53;
static struct nctempchar1 nctemp54 = {{ 3}, (char*)"\n\0"};
nctemp53=&nctemp54;
nctempchar1* nctemp51= nctemp53;
int nctemp55=LibePuts(nctemp49,nctemp51);
int nctemp57= 4;
int nctemp59=LibeFlush(nctemp57);
int nctemp61=LibeExit();
return 1;
}
int ErrSerror (nctempchar1 *file,nctempchar1 *fname,int lineno,nctempchar1 *s1,nctempchar1 *s2)
{
int nctemp64= 4;
struct nctempchar1 *nctemp68;
static struct nctempchar1 nctemp69 = {{ 7}, (char*)"file: \0"};
nctemp68=&nctemp69;
nctempchar1* nctemp66= nctemp68;
int nctemp70=LibePuts(nctemp64,nctemp66);
int nctemp72= 4;
nctempchar1* nctemp74= file;
int nctemp77=LibePuts(nctemp72,nctemp74);
int nctemp79= 4;
struct nctempchar1 *nctemp83;
static struct nctempchar1 nctemp84 = {{ 2}, (char*)" \0"};
nctemp83=&nctemp84;
nctempchar1* nctemp81= nctemp83;
int nctemp85=LibePuts(nctemp79,nctemp81);
int nctemp87= 4;
struct nctempchar1 *nctemp91;
static struct nctempchar1 nctemp92 = {{ 12}, (char*)" function: \0"};
nctemp91=&nctemp92;
nctempchar1* nctemp89= nctemp91;
int nctemp93=LibePuts(nctemp87,nctemp89);
int nctemp95= 4;
nctempchar1* nctemp97= fname;
int nctemp100=LibePuts(nctemp95,nctemp97);
int nctemp102= 4;
struct nctempchar1 *nctemp106;
static struct nctempchar1 nctemp107 = {{ 2}, (char*)" \0"};
nctemp106=&nctemp107;
nctempchar1* nctemp104= nctemp106;
int nctemp108=LibePuts(nctemp102,nctemp104);
int nctemp110= 4;
struct nctempchar1 *nctemp114;
static struct nctempchar1 nctemp115 = {{ 7}, (char*)" line \0"};
nctemp114=&nctemp115;
nctempchar1* nctemp112= nctemp114;
int nctemp116=LibePuts(nctemp110,nctemp112);
int nctemp118= 4;
int nctemp120= lineno;
int nctemp122=LibePuti(nctemp118,nctemp120);
int nctemp124= 4;
struct nctempchar1 *nctemp128;
static struct nctempchar1 nctemp129 = {{ 3}, (char*)": \0"};
nctemp128=&nctemp129;
nctempchar1* nctemp126= nctemp128;
int nctemp130=LibePuts(nctemp124,nctemp126);
nctempchar1 *nctemp132 =s1;
int nctemp131 =(nctemp132!=0);
if(nctemp131)
{
int nctemp137= 4;
nctempchar1* nctemp139= s1;
int nctemp142=LibePuts(nctemp137,nctemp139);
int nctemp144= 4;
struct nctempchar1 *nctemp148;
static struct nctempchar1 nctemp149 = {{ 3}, (char*)": \0"};
nctemp148=&nctemp149;
nctempchar1* nctemp146= nctemp148;
int nctemp150=LibePuts(nctemp144,nctemp146);
}
nctempchar1 *nctemp152 =s2;
int nctemp151 =(nctemp152!=0);
if(nctemp151)
{
int nctemp157= 4;
nctempchar1* nctemp159= s2;
int nctemp162=LibePuts(nctemp157,nctemp159);
int nctemp164= 4;
struct nctempchar1 *nctemp168;
static struct nctempchar1 nctemp169 = {{ 3}, (char*)"\n\0"};
nctemp168=&nctemp169;
nctempchar1* nctemp166= nctemp168;
int nctemp170=LibePuts(nctemp164,nctemp166);
}
int nctemp172= 4;
int nctemp174=LibeFlush(nctemp172);
int nctemp176=LibeExit();
return 1;
}
