#!/bin/sh

#el is a script to drive the loader using gcc

# Use one of these options for library location
#LIB=$EPS/Lib
#LIB=.

LIB=$EPS/Lib

FILES=" "
for i in $*
do
  FILES="$FILES $i" ;
done 
gcc -z muldefs -L$LIB $FILES -lecpu -ffast-math -lm
