#!/bin/sh

#elc is a script to drive the nvcc loader.

#Set library locations
LOCALLIB=.
EPSLIB=$EPS/Lib
LIB=$LOCALLIB

FILES=" "
for i in $*
do
  FILES="$FILES $i" ;
done 
nvcc -L$LIB $FILES -lecuda -lcudart

