#!/bin/sh

#el is a script to drive the loader using gcc

# Use one of these options for library location
#LIB=$EPS/Lib
#LIB=.

LIB=$EPS/Lib

FILES=" "
for i in $*
do
  FILES="$FILES $i" ;
done 
#nvcc -use_fast_math -Xcompiler "-z muldefs" --compiler-options "-ffast-math" -L$LIB $FILES -lecuda -lcudart
nvcc -L$LIB $FILES -lecuda -lcudart
