 #first void void void 0 1 void void void void void void 
 ZERO iconstant void void 0 0 void identifier lval void 48 global 
 EOS iconstant void void 0 0 void identifier lval void 0 global 
 NULL iconstant void void 0 0 void identifier lval void 0 global 
 NL iconstant void void 0 0 void identifier lval void 10 global 
 TAB iconstant void void 0 0 void identifier lval void 9 global 
 SPACE iconstant void void 0 0 void identifier lval void 32 global 
 PLUS iconstant void void 0 0 void identifier lval void 43 global 
 MINUS iconstant void void 0 0 void identifier lval void 45 global 
 STAR iconstant void void 0 0 void identifier lval void 42 global 
 LP iconstant void void 0 0 void identifier lval void 40 global 
 RP iconstant void void 0 0 void identifier lval void 41 global 
 LB iconstant void void 0 0 void identifier lval void 91 global 
 RB iconstant void void 0 0 void identifier lval void 93 global 
 LBR iconstant void void 0 0 void identifier lval void 123 global 
 RBR iconstant void void 0 0 void identifier lval void 125 global 
 COLON iconstant void void 0 0 void identifier lval void 58 global 
 SEMICOLON iconstant void void 0 0 void identifier lval void 59 global 
 COMMA iconstant void void 0 0 void identifier lval void 44 global 
 LT iconstant void void 0 0 void identifier lval void 60 global 
 GT iconstant void void 0 0 void identifier lval void 62 global 
 SLASH iconstant void void 0 0 void identifier lval void 47 global 
 BSLASH iconstant void void 0 0 void identifier lval void 92 global 
 ADRESS iconstant void void 0 0 void identifier lval void 38 global 
 ASSIGN iconstant void void 0 0 void identifier lval void 61 global 
 VBAR iconstant void void 0 0 void identifier lval void 124 global 
 EXLAM iconstant void void 0 0 void identifier lval void 33 global 
 POINT iconstant void void 0 0 void identifier lval void 46 global 
 DFN iconstant void void 0 0 void identifier lval void 34 global 
 SFN iconstant void void 0 0 void identifier lval void 39 global 
 HASH iconstant void void 0 0 void identifier lval void 35 global 
 stdin iconstant void void 0 0 void identifier lval void 2 global 
 stdout iconstant void void 0 0 void identifier lval void 3 global 
 stderr iconstant void void 0 0 void identifier lval void 4 global 
 LibeArrayex int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   line int void void 0 1 void identifier lval void void void 
   name char void array 1 1 void identifier lval void void void 
   ival int void void 0 1 void identifier lval void void void 
   index int void void 0 1 void identifier lval void void void 
   bound int void void 0 1 void identifier lval void void void 
  #self void LibeArrayex void 0 0 void void void void void void 
 LibeClearerr int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
  #self void LibeClearerr void 0 0 void void void void void void 
 LibeGeterrno int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
  #self void LibeGeterrno void 0 0 void void void void void void 
 LibeGeterrstr char fdef array 1 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
  #self void LibeGeterrstr void 0 0 void void void void void void 
 OK iconstant void void 0 0 void identifier lval void 1 global 
 ERR iconstant void void 0 0 void identifier lval void 0 global 
 EMPTY iconstant void void 0 0 void identifier lval void 2 global 
 EOF iconstant void void 0 0 void identifier lval void (-1) global 
 IOINITERR iconstant void void 0 0 void identifier lval void (-100) global 
 DOMAINERR iconstant void void 0 0 void identifier lval void (-101) global 
 RANGERR iconstant void void 0 0 void identifier lval void (-102) global 
 FMODEERR iconstant void void 0 0 void identifier lval void (-103) global 
 FMAXERR iconstant void void 0 0 void identifier lval void (-104) global 
 OPENERR iconstant void void 0 0 void identifier lval void (-105) global 
 CLOSERR iconstant void void 0 0 void identifier lval void (-106) global 
 PUSHERR iconstant void void 0 0 void identifier lval void (-107) global 
 MEMORYERR iconstant void void 0 0 void identifier lval void (-108) global 
 FNOREADERR iconstant void void 0 0 void identifier lval void (-109) global 
 FNOWRITERR iconstant void void 0 0 void identifier lval void (-110) global 
 READERR iconstant void void 0 0 void identifier lval void (-111) global 
 WRITERR iconstant void void 0 0 void identifier lval void (-112) global 
 ALLOCERR iconstant void void 0 0 void identifier lval void (-113) global 
 MainArg MainArg void void 0 1 structdef void void void void void 
  #first void void void 0 1 void void void void void void 
  arg char void array 1 1 void identifier lval void void void 
 Main int fdecl void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   MainArgs MainArg void array 1 1 struct identifier lval void void void 
  #self void Main void 0 0 void void void void void void 
 LibeInit int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
 LibeDelete int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
  #self void LibeDelete void 0 0 void void void void void void 
 LibeExit int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
  #self void LibeExit void 0 0 void void void void void void 
 LibeGetenv char fdef array 1 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   name char void array 1 1 void identifier lval void void void 
  #self void LibeGetenv void 0 0 void void void void void void 
 LibeOpen int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   name char void array 1 1 void identifier lval void void void 
   mode char void array 1 1 void identifier lval void void void 
 LibeClose int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   fp int void void 0 1 void identifier lval void void void 
 LibeGetc int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   fp int void void 0 1 void identifier lval void void void 
  #self void LibeGetc void 0 0 void void void void void void 
 LibeUngetc int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   fp int void void 0 1 void identifier lval void void void 
  #self void LibeUngetc void 0 0 void void void void void void 
 LibeGetw int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   fp int void void 0 1 void identifier lval void void void 
   text char void array 1 1 void identifier lval void void void 
 LibePs int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   s char void array 1 1 void identifier lval void void void 
  #self void LibePs void 0 0 void void void void void void 
 LibePi int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   n int void void 0 1 void identifier lval void void void 
  #self void LibePi void 0 0 void void void void void void 
 LibePf int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   r float void void 0 1 void identifier lval void void void 
  #self void LibePf void 0 0 void void void void void void 
 LibePutf int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   fp int void void 0 1 void identifier lval void void void 
   fval float void void 0 1 void identifier lval void void void 
   form char void array 1 1 void identifier lval void void void 
  #self void LibePutf void 0 0 void void void void void void 
 LibePutc int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   fp int void void 0 1 void identifier lval void void void 
   c int void void 0 1 void identifier lval void void void 
 LibePuts int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   fp int void void 0 1 void identifier lval void void void 
   s char void array 1 1 void identifier lval void void void 
 LibePuti int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   fp int void void 0 1 void identifier lval void void void 
   ival int void void 0 1 void identifier lval void void void 
  #self void LibePuti void 0 0 void void void void void void 
 LibeRead int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   fp int void void 0 1 void identifier lval void void void 
   n int void void 0 1 void identifier lval void void void 
   buffer char void array 1 1 void identifier lval void void void 
 LibeWrite int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   fp int void void 0 1 void identifier lval void void void 
   n int void void 0 1 void identifier lval void void void 
   buffer char void array 1 1 void identifier lval void void void 
 LibeSeek int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   fp int void void 0 1 void identifier lval void void void 
   pos int void void 0 1 void identifier lval void void void 
   flag int void void 0 1 void identifier lval void void void 
 LibeFlush int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   fp int void void 0 1 void identifier lval void void void 
  #self void LibeFlush void 0 0 void void void void void void 
 LibeStrlen int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   s char void array 1 1 void identifier lval void void void 
 LibeStrcmp int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   s char void array 1 1 void identifier lval void void void 
   t char void array 1 1 void identifier lval void void void 
 LibeStrev int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   s char void array 1 1 void identifier lval void void void 
 LibeStrsave char fdef array 1 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   s char void array 1 1 void identifier lval void void void 
 LibeStrcpy int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   s char void array 1 1 void identifier lval void void void 
   t char void array 1 1 void identifier lval void void void 
 LibeStrcat int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   s char void array 1 1 void identifier lval void void void 
   t char void array 1 1 void identifier lval void void void 
 LibeStradd char fdef array 1 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   t char void array 1 1 void identifier lval void void void 
   s char void array 1 1 void identifier lval void void void 
 LibeIsalpha int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   c int void void 0 1 void identifier lval void void void 
  #self void LibeIsalpha void 0 0 void void void void void void 
 LibeIsdigit int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   c int void void 0 1 void identifier lval void void void 
  #self void LibeIsdigit void 0 0 void void void void void void 
 LibeIsalnum int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   c int void void 0 1 void identifier lval void void void 
  #self void LibeIsalnum void 0 0 void void void void void void 
 LibeAtoi int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   s char void array 1 1 void identifier lval void void void 
 LibeItoa int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   n int void void 0 1 void identifier lval void void void 
   s char void array 1 1 void identifier lval void void void 
 LibeItoh int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   n int void void 0 1 void identifier lval void void void 
   s char void array 1 1 void identifier lval void void void 
 LibeAtof float fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   s char void array 1 1 void identifier lval void void void 
 LibeFtoa int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   f float void void 0 1 void identifier lval void void void 
   fmt char void array 1 1 void identifier lval void void void 
   s char void array 1 1 void identifier lval void void void 
 MFMIN iconstant void void 0 0 void identifier lval void 1 global 
 MFMAX iconstant void void 0 0 void identifier lval void 2 global 
 MEPSMIN iconstant void void 0 0 void identifier lval void 3 global 
 MEPSMAX iconstant void void 0 0 void identifier lval void 4 global 
 MLOG2 iconstant void void 0 0 void identifier lval void 5 global 
 LibeMach float fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   flag int void void 0 1 void identifier lval void void void 
  #self void LibeMach void 0 0 void void void void void void 
 LibeFabs float fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   x float void void 0 1 void identifier lval void void void 
  #self void LibeFabs void 0 0 void void void void void void 
 LibeFscale2 float fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   x float void void 0 1 void identifier lval void void void 
   n int void void 0 1 void identifier lval void void void 
 LibeGetfman2 float fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 193182736 1 void void void void void void 
   x float void void 0 1 void identifier lval void void void 
 LibeGetfexp2 int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 193176784 1 void void void void void void 
   x float void void 0 1 void identifier lval void void void 
 LibeFscale float fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 192952208 1 void void void void void void 
   x float void void 0 1 void identifier lval void void void 
   n int void void 0 1 void identifier lval void void void 
 LibeGetfman int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 193132144 1 void void void void void void 
   f float void void 0 1 void identifier lval void void void 
   maxdig int void void 0 1 void identifier lval void void void 
 LibeGetffman float fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 193167856 1 void void void void void void 
   f float void void 0 1 void identifier lval void void void 
 LibeGetmaxdig int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 193041904 1 void void void void void void 
   f float void void 0 1 void identifier lval void void void 
 LibeGetfexp int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 192388784 1 void void void void void void 
   f float void void 0 1 void identifier lval void void void 
 LibeClock float fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
  #self void LibeClock void 0 0 void void void void void void 
 LibeSetnb int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   nb int void void 0 1 void identifier lval void void void 
  #self void LibeSetnb void 0 0 void void void void void void 
 LibeSetnt int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   nt int void void 0 1 void identifier lval void void void 
  #self void LibeSetnt void 0 0 void void void void void void 
 LibeGetnb int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
  #self void LibeGetnb void 0 0 void void void void void void 
 LibeGetnt int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
  #self void LibeGetnt void 0 0 void void void void void void 
 LibeMod int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   n int void void 0 1 void identifier lval void void void 
   r int void void 0 1 void identifier lval void void void 
  #self void LibeMod void 0 0 void void void void void void 
 LibeSqrt float fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   x float void void 0 1 void identifier lval void void void 
 LibeLn float fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   x float void void 0 1 void identifier lval void void void 
 LibeExp float fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   x float void void 0 1 void identifier lval void void void 
 LibeSin float fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 193749648 1 void void void void void void 
   x float void void 0 1 void identifier lval void void void 
  #self void LibeSin void 0 0 void void void void void void 
 LibeCos float fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 193740720 1 void void void void void void 
   x float void void 0 1 void identifier lval void void void 
  #self void LibeCos void 0 0 void void void void void void 
 LibeTan float fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 193738736 1 void void void void void void 
   x float void void 0 1 void identifier lval void void void 
 LibeArcsin float fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   x float void void 0 1 void identifier lval void void void 
 LibeArccos float fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   x float void void 0 1 void identifier lval void void void 
 LibeArctan float fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   x float void void 0 1 void identifier lval void void void 
 LibePow float fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   base float void void 0 1 void identifier lval void void void 
   exponent float void void 0 1 void identifier lval void void void 
  #self void LibePow void 0 0 void void void void void void 
 LibeSystem int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   cmd char void array 1 1 void identifier lval void void void 
 EPS rconstant void void 0 0 void identifier lval void 1.1920928955078125e-07 global 
 EPSMAX rconstant void void 0 0 void identifier lval void 1.1920928955078125e-07 global 
 EPSMIN rconstant void void 0 0 void identifier lval void 5.9604644775390625e-08 global 
 MAXFDIG iconstant void void 0 0 void identifier lval void 6 global 
 FMAX rconstant void void 0 0 void identifier lval void 3.4028234663852886e+38 global 
 FMIN rconstant void void 0 0 void identifier lval void 1.1754943508222875e-38 global 
 EXPMAX iconstant void void 0 0 void identifier lval void 38 global 
 EXPMIN iconstant void void 0 0 void identifier lval void (-38) global 
 LOG2 rconstant void void 0 0 void identifier lval void 0.6931471805599453 global 
 LIMIT rconstant void void 0 0 void identifier lval void 2.4414062E-4 global 
 MBITS iconstant void void 0 0 void identifier lval void 24 global 
 FBITS iconstant void void 0 0 void identifier lval void 8 global 
 CPU iconstant void void 0 0 void identifier lval void 1 global 
 CUDA iconstant void void 0 0 void identifier lval void 2 global 
 HIP iconstant void void 0 0 void identifier lval void 3 global 
 ARCH iconstant void void 0 0 void identifier lval void 2 global 
 NB iconstant void void 0 0 void identifier lval void 1024 global 
 NT iconstant void void 0 0 void identifier lval void 1024 global 
 RunCreate int fdecl void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   name char void array 1 1 void identifier lval void void void 
  #self void RunCreate void 0 0 void void void void void void 
 RunClock float fdecl void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
  #self void RunClock void 0 0 void void void void void void 
 RunOpen int fdecl void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   name char void array 1 1 void identifier lval void void void 
   mode char void array 1 1 void identifier lval void void void 
  #self void RunOpen void 0 0 void void void void void void 
 RunClose int fdecl void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   fd int void void 0 1 void identifier lval void void void 
  #self void RunClose void 0 0 void void void void void void 
 RunRead int fdecl void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   fd int void void 0 1 void identifier lval void void void 
   lbuff int void void 0 1 void identifier lval void void void 
   buffer char void array 1 1 void identifier lval void void void 
  #self void RunRead void 0 0 void void void void void void 
 RunWrite int fdecl void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   fd int void void 0 1 void identifier lval void void void 
   lbuff int void void 0 1 void identifier lval void void void 
   buffer char void array 1 1 void identifier lval void void void 
  #self void RunWrite void 0 0 void void void void void void 
 RunSeek int fdecl void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   fd int void void 0 1 void identifier lval void void void 
   pos int void void 0 1 void identifier lval void void void 
   flag int void void 0 1 void identifier lval void void void 
  #self void RunSeek void 0 0 void void void void void void 
 RunGetenv char fdecl array 1 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   name char void array 1 1 void identifier lval void void void 
  #self void RunGetenv void 0 0 void void void void void void 
 RunStrcmp int fdecl void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   s char void array 1 1 void identifier lval void void void 
   t char void array 1 1 void identifier lval void void void 
  #self void RunStrcmp void 0 0 void void void void void void 
 RunStrlen int fdecl void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   s char void array 1 1 void identifier lval void void void 
  #self void RunStrlen void 0 0 void void void void void void 
 RunExit int fdecl void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
  #self void RunExit void 0 0 void void void void void void 
 RunSystem int fdecl void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   cmd char void array 1 1 void identifier lval void void void 
  #self void RunSystem void 0 0 void void void void void void 
 LibeErrno int void void 0 1 void identifier lval void void global 
 LibeErrstr char void array 1 1 void identifier lval void void global 
 LibeErrinit int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
  #self void LibeErrinit void 0 0 void void void void void void 
 LibeIoinit int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
 LibeMathinit int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
  #self void LibeMathinit void 0 0 void void void void void void 
 LibeIodelete int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
 LibeFdescr LibeFdescr void void 0 1 structdef void void void void void 
  #first void void void 0 1 void void void void void void 
  cnt int void void 0 1 void identifier lval void void void 
  ptr int void void 0 1 void identifier lval void void void 
  bufsize int void void 0 1 void identifier lval void void void 
  base char void array 1 1 void identifier lval void void void 
  readflg int void void 0 1 void identifier lval void void void 
  writflg int void void 0 1 void identifier lval void void void 
  unbflg int void void 0 1 void identifier lval void void void 
  errflg int void void 0 1 void identifier lval void void void 
  eoflg int void void 0 1 void identifier lval void void void 
  fd int void void 0 1 void identifier lval void void void 
 LIBEFMAX iconstant void void 0 0 void identifier lval void 40 global 
 LibeFarr LibeFdescr void array 1 1 struct identifier lval void void global 
 BUFSIZE iconstant void void 0 0 void identifier lval void 1024 global 
 LibeFillbuff int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   fp int void void 0 1 void identifier lval void void void 
 LibeFlushbuff int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   fp int void void 0 1 void identifier lval void void void 
 LibeTmpstr char void array 1 1 void identifier lval void void global 
 LibeFtoaf int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   mant int void void 0 1 void identifier lval void void void 
   nexp int void void 0 1 void identifier lval void void void 
   nfield int void void 0 1 void identifier lval void void void 
   nfrac int void void 0 1 void identifier lval void void void 
   s char void array 1 1 void identifier lval void void void 
 LibeFtoae int fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   mant int void void 0 1 void identifier lval void void void 
   nexp int void void 0 1 void identifier lval void void void 
   nfield int void void 0 1 void identifier lval void void void 
   nfrac int void void 0 1 void identifier lval void void void 
   s char void array 1 1 void identifier lval void void void 
 NBLOCKS int void void 0 1 void identifier lval void void global 
 NTHREADS int void void 0 1 void identifier lval void void global 
 LN2 rconstant void void 0 0 void identifier lval void 0.693147180559945309417232 global 
 LN2INV rconstant void void 0 0 void identifier lval void 1.4426950408889634073 global 
 SQRTHALF rconstant void void 0 0 void identifier lval void 0.70710678118654752440 global 
 PI rconstant void void 0 0 void identifier lval void 3.1415926535897932384626433832795028841972 global 
 PIINV rconstant void void 0 0 void identifier lval void 0.31830988618379067154 global 
 PIHALF rconstant void void 0 0 void identifier lval void 1.57079632679489661923132 global 
 PIBYFOUR rconstant void void 0 0 void identifier lval void 0.78539816339744830962 global 
 LibeSincosmax float void void 0 1 void identifier lval void void global 
 LibeSincoslim float void void 0 1 void identifier lval void void global 
 LibeLnmax float void void 0 1 void identifier lval void void global 
 LibeLnmin float void void 0 1 void identifier lval void void global 
 LibeSincos float fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   x float void void 0 1 void identifier lval void void void 
   y float void void 0 1 void identifier lval void void void 
   sign float void void 0 1 void identifier lval void void void 
 LibeAtan float fdef void 0 1 void void void void void void 
  #first void void void 0 1 void void void void void void 
  #arglist void void void 0 1 void void void void void void 
   #first void void void 0 1 void void void void void void 
   f float void void 0 1 void identifier lval void void void 
